package com.learnbyheart.bean;
// default package
// Generated Oct 26, 2014 4:31:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long id;
	private UserType userType;
	private String name;
	private String login;
	private String password;
	private String email;
//	private Set dictionaries = new HashSet(0);

	public User() {
	}

	public User(UserType userType, String name, String login, String password,
			String email) {
		this.userType = userType;
		this.name = name;
		this.login = login;
		this.password = password;
		this.email = email;
	}

//	public User(UserType userType, String name, String login, String password,
//			String email, Set dictionaries) {
//		this.userType = userType;
//		this.name = name;
//		this.login = login;
//		this.password = password;
//		this.email = email;
//		this.dictionaries = dictionaries;
//	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UserType getUserType() {
		return this.userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
//
//	public Set getDictionaries() {
//		return this.dictionaries;
//	}
//
//	public void setDictionaries(Set dictionaries) {
//		this.dictionaries = dictionaries;
//	}

}
