package com.learnbyheart.bean;
// default package
// Generated Oct 26, 2014 4:31:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType implements java.io.Serializable {

	private Long id;
	private String type;
	private List<User> users = new ArrayList<User>();

	public UserType() {
	}

	public UserType(String type) {
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

}
